import Tkinter as tk
from Tkinter import *

def fun():
    master = tk.Tk()

	# Reproduced under license from United States
	# Department of Agriculture.
	# Download a copy from from <URL: http://phaseit.net/tmp/gif/s1.gif>.
    image_file = "logo.gif"
    image = tk.PhotoImage(file = image_file)

        # Fill the screen.
    screen_width  = master.winfo_screenwidth()
    screen_height = master.winfo_screenheight()
    s = tk.Canvas(master, width  = screen_width,
			       height = screen_height)

        # Remove window-manager decorations:  don't allow
	# the user to destroy or iconify the splash screen.
    master.overrideredirect(1)

	# Center the image.
    s.create_image(screen_width / 2, screen_height / 2,
                   image = image)
    s.create_text( screen_width / 2, screen_height / 2,
		  text = "HOSTEL ACCESS SYSTEM\n\nAmarjeet singh \n\n161B027.",
		  fill = "magenta2", font = "normal 45")
    s.pack()

	# After five seconds--5000 milliseconds--remove the
	# splash screen.
    master.after(7000, lambda: master.destroy())
    master.mainloop()

fun()

def raise_frame(frame):
    frame.tkraise()

root=Tk()
root.title("@161B027")


f1 = Frame(root)
f2 = Frame(root)
f3 = Frame(root)
f4 = Frame(root)
f5 = Frame(root)
f6 = Frame(root)
f7 = Frame(root)
f8 = Frame(root)
f9 = Frame(root)
f10 = Frame(root)
f11= Frame(root)
f12= Frame(root)
f13= Frame(root)
f14= Frame(root)
f15= Frame(root)
f16= Frame(root)
f17= Frame(root)
f18= Frame(root)
f19= Frame(root)
f20= Frame(root)
f21= Frame(root)
f22= Frame(root)
f23= Frame(root)
f24= Frame(root)
f25= Frame(root)
f26= Frame(root)
f27= Frame(root)
f28= Frame(root)
f29= Frame(root)
f30= Frame(root)
f31= Frame(root)
f32= Frame(root)
f33= Frame(root)
f34= Frame(root)
f35= Frame(root)
f36= Frame(root)
f37= Frame(root)
f38= Frame(root)
f39= Frame(root)
f40= Frame(root)
f41= Frame(root)
f42= Frame(root)
f43= Frame(root)
f44= Frame(root)
f45= Frame(root)
f46= Frame(root)
f47= Frame(root)
f48= Frame(root)
f49= Frame(root)
f50= Frame(root)
f51= Frame(root)
f52= Frame(root)
f53= Frame(root)
f54= Frame(root)
f55= Frame(root)
f56= Frame(root)
f57= Frame(root)
f58= Frame(root)
f59= Frame(root)
f60= Frame(root)
f61= Frame(root)
f62= Frame(root)
f63= Frame(root)
f64= Frame(root)
f64= Frame(root)
f65= Frame(root)
f66= Frame(root)
f67= Frame(root)
f68= Frame(root)
f69= Frame(root)
f70= Frame(root)
f71= Frame(root)
f72= Frame(root)
f73= Frame(root)
f74= Frame(root)
f75= Frame(root)
f76= Frame(root)
f77= Frame(root)
f78= Frame(root)
f79= Frame(root)
f80= Frame(root)
f81= Frame(root)
f82= Frame(root)
f83= Frame(root)
f84= Frame(root)
f85= Frame(root)
f86= Frame(root)
f87= Frame(root)
f88= Frame(root)
f89= Frame(root)
f90= Frame(root)
f91= Frame(root)
f92= Frame(root)
f93= Frame(root)
f94= Frame(root)
f95= Frame(root)
f96= Frame(root)
f97= Frame(root)
f98= Frame(root)
f99= Frame(root)
f100= Frame(root)
f101= Frame(root)
f102= Frame(root)
f102= Frame(root)
f103= Frame(root)
f104= Frame(root)
f105= Frame(root)
f106= Frame(root)
f107= Frame(root)
f108= Frame(root)
f109= Frame(root)
f110= Frame(root)
f111= Frame(root)
f112= Frame(root)
f113= Frame(root)
f114= Frame(root)
f115= Frame(root)
f116= Frame(root)
f117= Frame(root)
f118= Frame(root)
f119= Frame(root)
f120= Frame(root)
f121= Frame(root)
f122= Frame(root)
f123= Frame(root)
f124= Frame(root)
f125= Frame(root)
f126= Frame(root)
f127= Frame(root)
f128= Frame(root)
f129= Frame(root)
f130= Frame(root)

for frame in (f1, f2, f3, f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,f14,f15,f16,f17,f18,f19,f20,f21,f22,f23,f24,f25,f26,f27,f28,f29,f30,f31,f32,f33,f34,f35,f36,f37,\
              f38,f39,f40,f41,f42,f43,f44,f45,f46,f47,f48,f49,f50,f51,f52,f53,f54,f55,f56,f57,f58,f59,f60,f61,f62,f63,f64,f65,f66,f67,f68,f69,f70,f71,f72,f73,f74,f75,f76,f77,f78,f79,f80,f81,f82,f83,f84,f85,f86,f87,f88,f89,f90,f91,f92,f93,f94,f95,f96,f97,f98,f99,f100,f101,f102,f103,f104,f105,f106,f107,f108,f109,f110,f111,f112,f113,f114,f115,f116,f117,f118,f119,f120,f121,f122,f123,f124,f125,f126,f127,f128,f129,f130):
    frame.grid(row=0, column=0, sticky='news')
w=Label(f1,text="HOSTEL ACCESS SYSTEM",font="times 15 bold").pack(fill=X,pady=10)
Label(f1,text='WELCOME TO H-22',font="times 15 bold",fg="red").pack()
Button(f1, text='H-22',bd=5,width=10, command=lambda:raise_frame(f2)).pack()
Label(f1, text='FRAME 1').pack()


Label(f2, text='FRAME 2').pack()
Label(f2, text='FLOOR').pack()
b1=Button(f2, text='   G FLOOR',bd=5,bg='red',width=10, command=lambda:raise_frame(f3)).pack()
b2=Button(f2, text=' 1st FLOOR',bd=5,bg='red',width=10, command=lambda:raise_frame(f4)).pack()

b3=Button(f2, text='2nd FLOOR',bd=5,bg='red',width=10, command=lambda:raise_frame(f5)).pack()

b4=Button(f2, text='3rd FLOOR',bd=5,bg='red',width=10, command=lambda:raise_frame(f6)).pack()

b5=Button(f2, text='<-',bd=5,bg='red',width=10, command=lambda:raise_frame(f1)).pack()



Label(f3, text='ROOMS').pack()
Label(f3, text='FRAME 3').pack()
Button(f3, text='1',bd=5,width=10, command=lambda:raise_frame(f7)).pack()
Button(f3, text='2',bd=5,width=10, command=lambda:raise_frame(f8)).pack()
Button(f3, text='3',bd=5,width=10, command=lambda:raise_frame(f9)).pack()
Button(f3, text='<-',bd=5,bg='red',width=10, command=lambda:raise_frame(f2)).pack()

Button(f4, text='33',bd=5,width=10, command=lambda:raise_frame(f10)).pack()
Button(f4, text='34',bd=5,width=10, command=lambda:raise_frame(f11)).pack()
Button(f4, text='35',bd=5,width=10, command=lambda:raise_frame(f12)).pack()
Button(f4, text='<-',bd=5,bg='red', width=10,command=lambda:raise_frame(f2)).pack()

Button(f5, text='70',bd=5,width=10, command=lambda:raise_frame(f13)).pack()
Button(f5, text='71',bd=5,width=10, command=lambda:raise_frame(f14)).pack()
Button(f5, text='72',bd=5,width=10, command=lambda:raise_frame(f15)).pack()
Button(f5, text='<-',bd=5,bg='red',width=10, command=lambda:raise_frame(f2)).pack()

Button(f6, text='107',bd=5,width=10, command=lambda:raise_frame(f16)).pack()
Button(f6, text='108',bd=5,width=10, command=lambda:raise_frame(f17)).pack()
Button(f6, text='109',bd=5,width=10, command=lambda:raise_frame(f18)).pack()
Button(f6, text='<-',bd=5,bg='red',width=10, command=lambda:raise_frame(f2)).pack()
#1
Label(f7, text='STUDENTS').pack()
Label(f7, text='FRAME 4').pack()
Button(f7, text='AYUSH',width=10, command=lambda:raise_frame(f19)).pack()
Button(f7, text='AMARJEET',width=10, command=lambda:raise_frame(f20)).pack()
Button(f7, text='ADARSH',width=10, command=lambda:raise_frame(f21)).pack()
Button(f7, text='<-', width=10,command=lambda:raise_frame(f3)).pack()
Button(f7, text='<-', width=10,command=lambda:raise_frame(f2)).pack()
#2
Label(f8, text='STUDENTS').pack()
Label(f8, text='FRAME 4').pack()
Button(f8, text='SPARSH', width=10,command=lambda:raise_frame(f22)).pack()
Button(f8, text='RITWIK', width=10,command=lambda:raise_frame(f23)).pack()
Button(f8, text='BHANU',width=10, command=lambda:raise_frame(f24)).pack()
Button(f8, text='<-', width=10,command=lambda:raise_frame(f3)).pack()
Button(f8, text='<-', width=10,command=lambda:raise_frame(f2)).pack()
#3
Label(f9, text='STUDENTS').pack()
Label(f9, text='FRAME 4').pack()
Button(f9, text='RAVI',width=10, command=lambda:raise_frame(f25)).pack()
Button(f9, text='RITIK',width=10, command=lambda:raise_frame(f26)).pack()
Button(f9, text='SAHIL ',width=10, command=lambda:raise_frame(f27)).pack()
Button(f9, text='<-', width=10,command=lambda:raise_frame(f3)).pack()
Button(f9, text='<-', width=10,command=lambda:raise_frame(f2)).pack()

Label(f10, text='STUDENTS').pack()
Label(f10, text='FRAME 4').pack()
Button(f10, text='SOHAN', width=10,command=lambda:raise_frame(f28)).pack()
Button(f10, text='ROHAN', width=10,command=lambda:raise_frame(f29)).pack()
Button(f10, text='MOHAN',width=10, command=lambda:raise_frame(f30)).pack()
Button(f10, text='<-',width=10, command=lambda:raise_frame(f4)).pack()
Button(f10, text='<-', width=10,command=lambda:raise_frame(f2)).pack()

Label(f11, text='STUDENTS').pack()
Label(f11, text='FRAME 4').pack()
Button(f11, text='RAVI R',width=10, command=lambda:raise_frame(f31)).pack()
Button(f11, text='SHIVAM',width=10, command=lambda:raise_frame(f32)).pack()
Button(f11, text='ADITYA',width=10, command=lambda:raise_frame(f33)).pack()
Button(f11, text='<-',width=10, command=lambda:raise_frame(f4)).pack()
Button(f11, text='<-', width=10,command=lambda:raise_frame(f2)).pack()

Label(f12, text='STUDENTS').pack()
Label(f12, text='FRAME 4').pack()
Button(f12, text='AMARDEEP',width=10, command=lambda:raise_frame(f34)).pack()
Button(f12, text='AMANDEEP',width=10, command=lambda:raise_frame(f35)).pack()
Button(f12, text='SANDEEP',width=10, command=lambda:raise_frame(f36)).pack()
Button(f12, text='<-',width=10, command=lambda:raise_frame(f4)).pack()
Button(f12, text='<-', width=10,command=lambda:raise_frame(f2)).pack()

Label(f13, text='STUDENTS').pack()
Label(f13, text='FRAME 4').pack()
Button(f13, text='AMAN',width=10, command=lambda:raise_frame(f37)).pack()
Button(f13, text='AMIT',width=10, command=lambda:raise_frame(f38)).pack()
Button(f13, text='AKASH',width=10, command=lambda:raise_frame(f39)).pack()
Button(f13, text='<-',width=10, command=lambda:raise_frame(f5)).pack()
Button(f13, text='<-', width=10,command=lambda:raise_frame(f2)).pack()

Label(f14, text='STUDENTS').pack()
Label(f14, text='FRAME 4').pack()
Button(f14, text='AYUSH',width=10, command=lambda:raise_frame(f40)).pack()
Button(f14, text='AJITESH',width=10, command=lambda:raise_frame(f41)).pack()
Button(f14, text='AYUSH',width=10, command=lambda:raise_frame(f42)).pack()
Button(f14, text='<-', width=10,command=lambda:raise_frame(f5)).pack()
Button(f14, text='<-', width=10,command=lambda:raise_frame(f2)).pack()

Label(f15, text='STUDENTS').pack()
Label(f15, text='FRAME 4').pack()
Button(f15, text='AJAY',width=10, command=lambda:raise_frame(f43)).pack()
Button(f15, text='SURYANSH',width=10, command=lambda:raise_frame(f44)).pack()
Button(f15, text='VIVEK',width=10, command=lambda:raise_frame(f45)).pack()
Button(f15, text='<-', width=10,command=lambda:raise_frame(f5)).pack()
Button(f15, text='<-', width=10,command=lambda:raise_frame(f2)).pack()

Label(f16, text='STUDENTS').pack()
Label(f16, text='FRAME 4').pack()
Button(f16, text='ABHISHEK', width=10,command=lambda:raise_frame(f46)).pack()
Button(f16, text='ABHISHEK',width=10, command=lambda:raise_frame(f47)).pack()
Button(f16, text='ABHISHEK', width=10,command=lambda:raise_frame(f48)).pack()
Button(f16, text='<-', width=10,command=lambda:raise_frame(f6)).pack()
Button(f16, text='<-', width=10,command=lambda:raise_frame(f2)).pack()


Label(f17, text='STUDENTS').pack()
Label(f17, text='FRAME 4').pack()
Button(f17, text='AKSHAY',width=10, command=lambda:raise_frame(f49)).pack()
Button(f17, text='AKSHAY',width=10, command=lambda:raise_frame(f50)).pack()
Button(f17, text='AKSHIT',width=10, command=lambda:raise_frame(f51)).pack()
Button(f17, text='<-',width=10, command=lambda:raise_frame(f6)).pack()
Button(f17, text='<-', width=10,command=lambda:raise_frame(f2)).pack()

Label(f18, text='STUDENTS').pack()
Label(f18, text='FRAME 4').pack()
Button(f18, text='ROHIT',width=10, command=lambda:raise_frame(f52)).pack()
Button(f18, text='SOBHIT', width=10,command=lambda:raise_frame(f53)).pack()
Button(f18, text='DEEPAK',width=10, command=lambda:raise_frame(f54)).pack()
Button(f18, text='<-', width=10,command=lambda:raise_frame(f6)).pack()
Button(f18, text='<-', width=10,command=lambda:raise_frame(f2)).pack()
#NAME info

Label(f19, text='INFORMATION').pack()
Label(f19, text='FRAME 5').pack()
Button(f19, text='PERSONAL',width=10, command=lambda:raise_frame(f55)).pack()
Button(f19, text='ACADEMICS',width=10, command=lambda:raise_frame(f56)).pack()
Button(f19, text='<-', width=10,command=lambda:raise_frame(f7)).pack()


Label(f20, text='INFORMATION').pack()
Label(f20, text='FRAME 5').pack()
Button(f20, text='PERSONAL',width=10, command=lambda:raise_frame(f57)).pack()
Button(f20, text='ACADEMICS',width=10, command=lambda:raise_frame(f58)).pack()
Button(f20, text='<-',width=10, command=lambda:raise_frame(f7)).pack()

Label(f21, text='INFORMATION').pack()
Label(f21, text='FRAME 5').pack()
Button(f21, text='PERSONAL',width=10, command=lambda:raise_frame(f59)).pack()
Button(f21, text='ACADEMICS',width=10, command=lambda:raise_frame(f60)).pack()
Button(f21, text='<-',width=10, command=lambda:raise_frame(f7)).pack()

Label(f22, text='INFORMATION').pack()
Label(f22, text='FRAME 5').pack()
Button(f22, text='PERSONAL',width=10, command=lambda:raise_frame(f61)).pack()
Button(f22, text='ACADEMICS',width=10, command=lambda:raise_frame(f62)).pack()
Button(f22, text='<-',width=10, command=lambda:raise_frame(f8)).pack()

Label(f23, text='INFORMATION').pack()
Label(f23, text='FRAME 5').pack()
Button(f23, text='PERSONAL',width=10, command=lambda:raise_frame(f63)).pack()
Button(f23, text='ACADEMICS',width=10, command=lambda:raise_frame(f64)).pack()
Button(f23, text='<-',width=10, command=lambda:raise_frame(f8)).pack()

Label(f24, text='INFORMATION').pack()
Label(f24, text='FRAME 5').pack()
Button(f24, text='PERSONAL',width=10, command=lambda:raise_frame(f65)).pack()
Button(f24, text='ACADEMICS',width=10, command=lambda:raise_frame(f66)).pack()
Button(f24, text='<-',width=10, command=lambda:raise_frame(f8)).pack()

Label(f25, text='INFORMATION').pack()
Label(f25, text='FRAME 5').pack()
Button(f25, text='PERSONAL',width=10, command=lambda:raise_frame(f67)).pack()
Button(f25, text='ACADEMICS',width=10, command=lambda:raise_frame(f68)).pack()
Button(f25, text='<-',width=10, command=lambda:raise_frame(f9)).pack()
#26

Label(f26, text='INFORMATION').pack()
Label(f26, text='FRAME 5').pack()
Button(f26, text='PERSONAL',width=10, command=lambda:raise_frame(f69)).pack()
Button(f26, text='ACADEMICS',width=10, command=lambda:raise_frame(f70)).pack()
Button(f26, text='<-',width=10, command=lambda:raise_frame(f9)).pack()

#27
Label(f27, text='INFORMATION').pack()
Label(f27, text='FRAME 5').pack()
Button(f27, text='PERSONAL',width=10, command=lambda:raise_frame(f71)).pack()
Button(f27, text='ACADEMICS',width=10, command=lambda:raise_frame(f72)).pack()
Button(f27, text='<-',width=10, command=lambda:raise_frame(f9)).pack()

Label(f28, text='INFORMATION').pack()
Label(f28, text='FRAME 5').pack()
Button(f28, text='PERSONAL',width=10, command=lambda:raise_frame(f73)).pack()
Button(f28, text='ACADEMICS',width=10, command=lambda:raise_frame(f74)).pack()
Button(f28, text='<-',width=10, command=lambda:raise_frame(f10)).pack()

Label(f29, text='INFORMATION').pack()
Label(f29, text='FRAME 5').pack()
Button(f29, text='PERSONAL',width=10, command=lambda:raise_frame(f75)).pack()
Button(f29, text='ACADEMICS',width=10, command=lambda:raise_frame(f76)).pack()
Button(f29, text='<-',width=10, command=lambda:raise_frame(f10)).pack()

Label(f30, text='INFORMATION').pack()
Label(f30, text='FRAME 5').pack()
Button(f30, text='PERSONAL',width=10, command=lambda:raise_frame(f77)).pack()
Button(f30, text='ACADEMICS',width=10, command=lambda:raise_frame(f78)).pack()
Button(f30, text='<-', width=10,command=lambda:raise_frame(f10)).pack()

#31 to 40
Label(f31, text='INFORMATION').pack()
Label(f31, text='FRAME 5').pack()
Button(f31, text='PERSONAL',width=10, command=lambda:raise_frame(f79)).pack()
Button(f31, text='ACADEMICS', width=10,command=lambda:raise_frame(f80)).pack()
Button(f31, text='<-', width=10,command=lambda:raise_frame(f11)).pack()

Label(f32, text='INFORMATION').pack()
Label(f32, text='FRAME 5').pack()
Button(f32, text='PERSONAL',width=10, command=lambda:raise_frame(f81)).pack()
Button(f32, text='ACADEMICS',width=10, command=lambda:raise_frame(f82)).pack()
Button(f32, text='<-', width=10,command=lambda:raise_frame(f11)).pack()

Label(f33, text='INFORMATION').pack()
Label(f33, text='FRAME 5').pack()
Button(f33, text='PERSONAL',width=10, command=lambda:raise_frame(f83)).pack()
Button(f33, text='ACADEMICS',width=10, command=lambda:raise_frame(f84)).pack()
Button(f33, text='<-',width=10, command=lambda:raise_frame(f11)).pack()


Label(f34, text='INFORMATION').pack()
Label(f34, text='FRAME 5').pack()
Button(f34, text='PERSONAL',width=10, command=lambda:raise_frame(f85)).pack()
Button(f34, text='ACADEMICS',width=10, command=lambda:raise_frame(f86)).pack()
Button(f34, text='<-', width=10,command=lambda:raise_frame(f12)).pack()

Label(f35, text='INFORMATION').pack()
Label(f35, text='FRAME 5').pack()
Button(f35, text='PERSONAL',width=10, command=lambda:raise_frame(f87)).pack()
Button(f35, text='ACADEMICS', width=10,command=lambda:raise_frame(f88)).pack()
Button(f35, text='<-',width=10, command=lambda:raise_frame(f12)).pack()

Label(f36, text='INFORMATION').pack()
Label(f36, text='FRAME 5').pack()
Button(f36, text='PERSONAL',width=10, command=lambda:raise_frame(f89)).pack()
Button(f36, text='ACADEMICS', width=10,command=lambda:raise_frame(f90)).pack()
Button(f36, text='<-',width=10, command=lambda:raise_frame(f12)).pack()


Label(f37, text='INFORMATION').pack()
Label(f37, text='FRAME 5').pack()
Button(f37, text='PERSONAL', width=10,command=lambda:raise_frame(f91)).pack()
Button(f37, text='ACADEMICS', width=10,command=lambda:raise_frame(f92)).pack()
Button(f37, text='<-', width=10,command=lambda:raise_frame(f13)).pack()

Label(f38, text='INFORMATION').pack()
Label(f38, text='FRAME 5').pack()
Button(f38, text='PERSONAL',width=10, command=lambda:raise_frame(f93)).pack()
Button(f38, text='ACADEMICS',width=10, command=lambda:raise_frame(f94)).pack()
Button(f38, text='<-',width=10, command=lambda:raise_frame(f13)).pack()

Label(f39, text='INFORMATION').pack()
Label(f39, text='FRAME 5').pack()
Button(f39, text='PERSONAL', width=10,command=lambda:raise_frame(f95)).pack()
Button(f39, text='ACADEMICS', width=10,command=lambda:raise_frame(f96)).pack()
Button(f39, text='<-',width=10, command=lambda:raise_frame(f13)).pack()

Label(f40, text='INFORMATION').pack()
Label(f40, text='FRAME 5').pack()
Button(f40, text='PERSONAL', width=10,command=lambda:raise_frame(f97)).pack()
Button(f40, text='ACADEMICS', width=10,command=lambda:raise_frame(f98)).pack()
Button(f40, text='<-', width=10,command=lambda:raise_frame(f14)).pack()
#41 to 50

Label(f41, text='INFORMATION').pack()
Label(f41, text='FRAME 5').pack()
Button(f41, text='PERSONAL',width=10, command=lambda:raise_frame(f99)).pack()
Button(f41, text='ACADEMICS', width=10,command=lambda:raise_frame(f100)).pack()
Button(f41, text='<-',width=10, command=lambda:raise_frame(f14)).pack()

Label(f42, text='INFORMATION').pack()
Label(f42, text='FRAME 5').pack()
Button(f42, text='PERSONAL',width=10, command=lambda:raise_frame(f101)).pack()
Button(f42, text='ACADEMICS',width=10, command=lambda:raise_frame(f102)).pack()
Button(f42, text='<-',width=10, command=lambda:raise_frame(f14)).pack()

Label(f43, text='INFORMATION').pack()
Label(f43, text='FRAME 5').pack()
Button(f43, text='PERSONAL',width=10, command=lambda:raise_frame(f103)).pack()
Button(f43, text='ACADEMICS',width=10, command=lambda:raise_frame(f104)).pack()
Button(f43, text='<-',width=10, command=lambda:raise_frame(f15)).pack()

Label(f44, text='INFORMATION').pack()
Label(f44, text='FRAME 5').pack()
Button(f44, text='PERSONAL',width=10, command=lambda:raise_frame(f105)).pack()
Button(f44, text='ACADEMICS',width=10, command=lambda:raise_frame(f106)).pack()
Button(f44, text='<-',width=10, command=lambda:raise_frame(f15)).pack()

Label(f45, text='INFORMATION').pack()
Label(f45, text='FRAME 5').pack()
Button(f45, text='PERSONAL',width=10, command=lambda:raise_frame(f107)).pack()
Button(f45, text='ACADEMICS', width=10,command=lambda:raise_frame(f108)).pack()
Button(f45, text='<-',width=10, command=lambda:raise_frame(f15)).pack()

Label(f46, text='INFORMATION').pack()
Label(f46, text='FRAME 5').pack()
Button(f46, text='PERSONAL', width=10,command=lambda:raise_frame(f109)).pack()
Button(f46, text='ACADEMICS', width=10,command=lambda:raise_frame(f110)).pack()
Button(f46, text='<-', width=10,command=lambda:raise_frame(f16)).pack()

Label(f47, text='INFORMATION').pack()
Label(f47, text='FRAME 5').pack()
Button(f47, text='PERSONAL', width=10,command=lambda:raise_frame(f111)).pack()
Button(f47, text='ACADEMICS', width=10,command=lambda:raise_frame(f112 )).pack()
Button(f47, text='<-', width=10,command=lambda:raise_frame(f16)).pack()

Label(f48, text='INFORMATION').pack()
Label(f48, text='FRAME 5').pack()
Button(f48, text='PERSONAL', width=10,command=lambda:raise_frame(f113)).pack()
Button(f48, text='ACADEMICS', width=10,command=lambda:raise_frame(f114)).pack()
Button(f48, text='<-', width=10,command=lambda:raise_frame(f16)).pack()

Label(f49, text='INFORMATION').pack()
Label(f49, text='FRAME 5').pack()
Button(f49, text='PERSONAL', width=10,command=lambda:raise_frame(f115)).pack()
Button(f49, text='ACADEMICS', width=10,command=lambda:raise_frame(f116)).pack()
Button(f49, text='<-', width=10,command=lambda:raise_frame(f17)).pack()

Label(f50, text='INFORMATION').pack()
Label(f50, text='FRAME 5').pack()
Button(f50, text='PERSONAL', width=10,command=lambda:raise_frame(f117)).pack()
Button(f50, text='ACADEMICS', width=10,command=lambda:raise_frame(f118)).pack()
Button(f50, text='<-', width=10,command=lambda:raise_frame(f17)).pack()

Label(f51, text='INFORMATION').pack()
Label(f51, text='FRAME 5').pack()
Button(f51, text='PERSONAL', width=10,command=lambda:raise_frame(f119)).pack()
Button(f51, text='ACADEMICS',width=10, command=lambda:raise_frame(f120)).pack()
Button(f51, text='<-',width=10, command=lambda:raise_frame(f17)).pack()

Label(f52, text='INFORMATION').pack()
Label(f52, text='FRAME 5').pack()
Button(f52, text='PERSONAL', width=10,command=lambda:raise_frame(f121)).pack()
Button(f52, text='ACADEMICS', width=10,command=lambda:raise_frame(f122)).pack()
Button(f52, text='<-',width=10, command=lambda:raise_frame(f18)).pack()

Label(f53, text='INFORMATION').pack()
Label(f53, text='FRAME 5').pack()
Button(f53, text='PERSONAL', width=10,command=lambda:raise_frame(f123)).pack()
Button(f53, text='ACADEMICS',width=10, command=lambda:raise_frame(f124)).pack()
Button(f53, text='<-',width=10, command=lambda:raise_frame(f18)).pack()

Label(f54, text='INFORMATION').pack()
Label(f54, text='FRAME 5').pack()
Button(f54, text='PERSONAL', width=10,command=lambda:raise_frame(f125)).pack()
Button(f54, text='ACADEMICS', width=10,command=lambda:raise_frame(f126)).pack()
Button(f54, text='<-', width=10,command=lambda:raise_frame(f18)).pack()

Label(f55, text='PERSONAL').pack()
Label(f55, text='FRAME 6').pack()
Label(f55,text="AYUSH SRIVASTAVA",font="times 15 bold").pack()
Label(f55,text="FATHER'SNAME:xyz").pack()
Label(f55,text="CITY:Lucknow").pack()
Label(f55,text="STATE:xyz").pack()
Label(f55,text="MOBILE NO.:1234569870").pack()
Button(f55, text='<-',bg="red",width=10, command=lambda:raise_frame(f19)).pack()
Button(f55, text='<-',bg="red",width=10, command=lambda:raise_frame(f1)).pack()
Label(f56, text='ACADEMICS').pack()
Label(f56, text='AYUSH SRIVASTAVA',font="times 15 bold").pack()
Label(f56,text="ERNO,:161B062").pack()
Label(f56,text="SEMESTER 1=SGPA:7.8   CGPA:7.8",bg="blue").pack()
Label(f56,text="SEMESTER 2=SGPA:7.8   CGPA:7.8",bg="blue").pack()
Label(f56,text="TOTAL =7.8",bg="blue").pack()
Button(f56, text='<-',bg="red", width=10,command=lambda:raise_frame(f19)).pack()
Button(f56, text='<-',bg="red",width=10, command=lambda:raise_frame(f1)).pack()


Label(f57, text='PERSONAL').pack()
Label(f57, text='FRAME 6').pack()
Label(f57,text="AMARJEET SINGH",font="times 15 bold").pack()
Label(f57,text="FATHER'SNAME:xyz").pack()
Label(f57,text="CITY:xyz").pack()
Label(f57,text="STATE:xyz").pack()
Label(f57,text="MOBILE NO.:1234569870").pack()
Button(f57, text='<-',bg="red", width=10,command=lambda:raise_frame(f20)).pack()
Button(f57, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f58, text='ACADEMICS').pack()
Label(f58, text='FRAME 7').pack()
Label(f58,text="AMARJEET SINGH",font="times 15 bold").pack()
Label(f58,text="ERNO,:161B027").pack()
Label(f58,text="SEMESTER 1=SGPA:7.8   CGPA:7.8",bg="blue").pack()
Label(f58,text="SEMESTER 2=SGPA:7.8  CGPA:7.8",bg="blue").pack()
Label(f58,text="TOTAL =7.8",bg="blue").pack()
Button(f58, text='<-',bg="red",width=10, command=lambda:raise_frame(f20)).pack()
Button(f58, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()


Label(f59, text='PERSONAL').pack()
Label(f59, text='FRAME 6').pack()
Label(f59,text="ADARSH KUMAR",font="times 15 bold").pack()
Label(f59,text="FATHER'SNAME:xyz").pack()
Label(f59,text="CITY:xyz").pack()
Label(f59,text="STATE:xyz").pack()
Label(f59,text="MOBILE NO.:1234569870").pack()
Button(f59, text='<-',bg="red",width=10, command=lambda:raise_frame(f21)).pack()
Button(f59, text='<-',bg="red",width=10, command=lambda:raise_frame(f1)).pack()

Label(f60, text='ACADEMICS').pack()
Label(f60, text='FRAME 7').pack()
Label(f59,text="ADARSH KUMAR",font="times 15 bold").pack()
Label(f60,text="ERNO,:161B011").pack()
Label(f60,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f60,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f60,text="TOTAL =7.6",bg="blue").pack()
Button(f60, text='<-',bg="red",width=10, command=lambda:raise_frame(f21)).pack()
Button(f60, text='<-',bg="red",width=10, command=lambda:raise_frame(f1)).pack()


Label(f61, text='PERSONAL').pack()
Label(f61, text='FRAME 6').pack()
Label(f61,text="SPARSH",font="times 15 bold").pack()
Label(f61,text="FATHER'SNAME:xyz").pack()
Label(f61,text="CITY:xyz").pack()
Label(f61,text="STATE:xyz").pack()
Label(f61,text="MOBILE NO.:1234569870").pack()
Button(f61, text='<-',bg="red",width=10, command=lambda:raise_frame(f22)).pack()
Button(f61, text='<-',bg="red",width=10, command=lambda:raise_frame(f1)).pack()

Label(f62, text='ACADEMICS').pack()
Label(f62, text='FRAME 7').pack()
Label(f61,text="SPARSH",font="times 15 bold").pack()
Label(f62,text="ERNO,:161B198").pack()
Label(f62,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f62,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f62,text="TOTAL =7.6",bg="blue").pack()
Button(f62, text='<-',bg="red", width=10,command=lambda:raise_frame(f22)).pack()
Button(f62, text='<-',bg="red",width=10, command=lambda:raise_frame(f1)).pack()

Label(f63, text='PERSONAL').pack()
Label(f63, text='FRAME 6').pack()
Label(f63,text="RITWIK SHANKAR",font="times 15 bold").pack()
Label(f63,text="FATHER'SNAME:xyz").pack()
Label(f63,text="CITY:xyz").pack()
Label(f63,text="STATE:xyz").pack()
Label(f63,text="MOBILE NO.:1234569870").pack()
Button(f63, text='<-',bg="red", width=10,command=lambda:raise_frame(f23)).pack()
Button(f63, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f64, text='ACADEMICS').pack()
Label(f64, text='FRAME 7').pack()
Label(f64,text="RITWIK SHANKAR",font="times 15 bold").pack()
Label(f64,text="ERNO,:161B176").pack()
Label(f64,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f64,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f64,text="TOTAL =7.6",bg="blue").pack()
Button(f64, text='<-',bg="red", width=10,command=lambda:raise_frame(f23)).pack()
Button(f64, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f65, text='PERSONAL').pack()
Label(f65, text='FRAME 6').pack()
Label(f65,text="BHANU PRATAP",font="times 15 bold").pack()
Label(f65,text="FATHER'SNAME:xyz").pack()
Label(f65,text="CITY:xyz").pack()
Label(f65,text="STATE:xyz").pack()
Label(f65,text="MOBILE NO.:1234569870").pack()
Button(f65, text='<-',bg="red", width=10,command=lambda:raise_frame(f24)).pack()
Button(f65, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f66, text='ACADEMICS').pack()
Label(f66, text='FRAME 7').pack()
Label(f66,text="BHANU PRATAP",font="times 15 bold").pack()
Label(f66,text="ERNO,:161B065").pack()
Label(f66,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f66,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f66,text="TOTAL =7.6",bg="blue").pack()
Button(f66, text='<-',bg="red", width=10,command=lambda:raise_frame(f24)).pack()
Button(f66, text='<-',bg="red",width=10, command=lambda:raise_frame(f1)).pack()


Label(f67, text='PERSONAL').pack()
Label(f67, text='FRAME 6').pack()
Label(f67,text="RAVI",font="times 15 bold").pack()
Label(f67,text="FATHER'SNAME:xyz").pack()
Label(f67,text="CITY:xyz").pack()
Label(f67,text="STATE:xyz").pack()
Label(f67,text="MOBILE NO.:1234569870").pack()
Button(f67, text='<-',bg="red", width=10,command=lambda:raise_frame(f25)).pack()
Button(f67, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f68, text='ACADEMICS').pack()
Label(f68, text='FRAME 7').pack()
Label(f68,text="RAVI",font="times 15 bold").pack()
Label(f68,text="ERNO,:161B170").pack()
Label(f68,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f68,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f68,text="TOTAL =7.6",bg="blue").pack()
Button(f68, text='<-',bg="red", width=10,command=lambda:raise_frame(f25)).pack()
Button(f68, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()


Label(f69, text='PERSONAL').pack()
Label(f69, text='FRAME 6').pack()
Label(f67,text="RITIK RAJ SRIVASTAVA",font="times 15 bold").pack()
Label(f69,text="FATHER'SNAME:xyz").pack()
Label(f69,text="CITY:xyz").pack()
Label(f69,text="STATE:xyz").pack()
Label(f69,text="MOBILE NO.:1234569870").pack()
Button(f69, text='<-',bg="red", width=10,command=lambda:raise_frame(f26)).pack()
Button(f69, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f70, text='ACADEMICS').pack()
Label(f70, text='FRAME 7').pack()
Label(f67,text="RITIK RAJ SRIVASTAVA",font="times 15 bold").pack()
Label(f70,text="ERNO,:161B178").pack()
Label(f70,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f70,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f70,text="TOTAL =7.6",bg="blue").pack()
Button(f70, text='<-',bg="red", width=10,command=lambda:raise_frame(f26)).pack()
Button(f70, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f71, text='PERSONAL').pack()
Label(f71, text='FRAME 6').pack()
Label(f71,text="SAHIL AWASTHI",font="times 15 bold").pack()
Label(f71,text="FATHER'SNAME:xyz").pack()
Label(f71,text="CITY:xyz").pack()
Label(f71,text="STATE:xyz").pack()
Label(f71,text="MOBILE NO.:1234569870").pack()
Button(f71, text='<-',bg="red",width=10, command=lambda:raise_frame(f27)).pack()
Button(f71, text='<-',bg="red",width=10, command=lambda:raise_frame(f1)).pack()

Label(f72, text='ACADEMICS').pack()
Label(f72, text='FRAME 7').pack()
Label(f72,text="SAHIL AWASTHI",font="times 15 bold").pack()
Label(f72,text="ERNO,:161B205").pack()
Label(f72,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f72,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f72,text="TOTAL =7.6",bg="blue").pack()
Button(f72, text='<-',bg="red", width=10,command=lambda:raise_frame(f27)).pack()
Button(f72, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f73, text='PERSONAL').pack()
Label(f73, text='FRAME 6').pack()
Label(f73,text="SOHAN",font="times 15 bold").pack()
Label(f73,text="FATHER'SNAME:xyz").pack()
Label(f73,text="CITY:xyz").pack()
Label(f73,text="STATE:xyz").pack()
Label(f73,text="MOBILE NO.:1234569870").pack()
Button(f73, text='<-',bg="red",width=10, command=lambda:raise_frame(f28)).pack()
Button(f73, text='<-',bg="red",width=10, command=lambda:raise_frame(f1)).pack()

Label(f74, text='ACADEMICS').pack()
Label(f74, text='FRAME 7').pack()
Label(f74,text="SOHAN",font="times 15 bold").pack()
Label(f74,text="ERNO,:161B185").pack()
Label(f74,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f74,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f74,text="TOTAL =7.6",bg="blue").pack()
Button(f74, text='<-',bg="red",width=10, command=lambda:raise_frame(f28)).pack()
Button(f74, text='<-',bg="red",width=10, command=lambda:raise_frame(f1)).pack()


Label(f75, text='PERSONAL').pack()
Label(f75, text='FRAME 6').pack()
Label(f75,text="ROHAN",font="times 15 bold").pack()
Label(f75,text="FATHER'SNAME:xyz").pack()
Label(f75,text="CITY:xyz").pack()
Label(f75,text="STATE:xyz").pack()
Label(f75,text="MOBILE NO.:1234569870").pack()
Button(f75, text='<-',bg="red", width=10,command=lambda:raise_frame(f29)).pack()
Button(f75, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f76, text='ACADEMICS').pack()
Label(f76, text='FRAME 7').pack()
Label(f75,text="ROHAN",font="times 15 bold").pack()
Label(f76,text="ERNO,:161B184").pack()
Label(f76,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f76,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f76,text="TOTAL =7.6",bg="blue").pack()
Button(f76, text='<-',bg="red",width=10, command=lambda:raise_frame(f29)).pack()
Button(f76, text='<-',bg="red",width=10, command=lambda:raise_frame(f1)).pack()

Label(f77, text='PERSONAL').pack()
Label(f77, text='FRAME 6').pack()
Label(f77,text="MOHAN",font="times 15 bold").pack()
Label(f77,text="FATHER'SNAME:xyz").pack()
Label(f77,text="CITY:xyz").pack()
Label(f77,text="STATE:xyz").pack()
Label(f77,text="MOBILE NO.:1234569870").pack()
Button(f77, text='<-',bg="red", width=10,command=lambda:raise_frame(f30)).pack()
Button(f77, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f78, text='ACADEMICS').pack()
Label(f78, text='FRAME 7').pack()
Label(f78,text="MOHAN",font="times 15 bold").pack()
Label(f78,text="ERNO,:161B205").pack()
Label(f78,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f78,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f78,text="TOTAL =7.6",bg="blue").pack()
Button(f78, text='<-',bg="red",width=10, command=lambda:raise_frame(f30)).pack()
Button(f78, text='<-',bg="red",width=10, command=lambda:raise_frame(f1)).pack()


Label(f79, text='PERSONAL').pack()
Label(f79, text='FRAME 6').pack()
Label(f79,text="RAVIR",font="times 15 bold").pack()
Label(f79,text="FATHER'SNAME:xyz").pack()
Label(f79,text="CITY:xyz").pack()
Label(f79,text="STATE:xyz").pack()
Label(f79,text="MOBILE NO.:1234569870").pack()
Button(f79, text='<-',bg="red",width=10, command=lambda:raise_frame(f31)).pack()
Button(f79, text='<-',bg="red",width=10, command=lambda:raise_frame(f1)).pack()

Label(f80, text='ACADEMICS').pack()
Label(f80, text='FRAME 7').pack()
Label(f80,text="RAVIR",font="times 15 bold").pack()
Label(f80,text="ERNO,:161B205").pack()
Label(f80,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f80,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f80,text="TOTAL =7.6",bg="blue").pack()
Button(f80, text='<-',bg="red",width=10, command=lambda:raise_frame(f31)).pack()
Button(f80, text='<-',bg="red",width=10, command=lambda:raise_frame(f1)).pack()

Label(f81, text='PERSONAL').pack()
Label(f81, text='FRAME 6').pack()
Label(f81,text="SHIVAM RAO",font="times 15 bold").pack()
Label(f81,text="FATHER'SNAME:xyz").pack()
Label(f81,text="CITY:xyz").pack()
Label(f81,text="STATE:xyz").pack()
Label(f81,text="MOBILE NO.:1234569870").pack()
Button(f81, text='<-',bg="red", width=10,command=lambda:raise_frame(f32)).pack()
Button(f81, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f82, text='ACADEMICS').pack()
Label(f82, text='FRAME 7').pack()
Label(f82,text="SHIVAM RAO",font="times 15 bold").pack()
Label(f82,text="ERNO,:161B206").pack()
Label(f82,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f82,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f82,text="TOTAL =7.6",bg="blue").pack()
Button(f82, text='<-',bg="red", width=10,command=lambda:raise_frame(f32)).pack()
Button(f82, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f83, text='PERSONAL').pack()
Label(f83, text='FRAME 6').pack()
Label(f83,text="ADITYA SINGH",font="times 15 bold").pack()
Label(f83,text="FATHER'SNAME:xyz").pack()
Label(f83,text="CITY:xyz").pack()
Label(f83,text="STATE:xyz").pack()
Label(f83,text="MOBILE NO.:1234569870").pack()
Button(f83, text='<-',bg="red", width=10,command=lambda:raise_frame(f33)).pack()
Button(f83, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f84, text='ACADEMICS').pack()
Label(f84, text='FRAME 7').pack()
Label(f83,text="ADITYA SINGH",font="times 15 bold").pack()
Label(f84,text="ERNO,:161B013").pack()
Label(f84,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f84,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f84,text="TOTAL =7.6",bg="blue").pack()
Button(f84, text='<-',bg="red", width=10,command=lambda:raise_frame(f33)).pack()
Button(f84, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()


Label(f85, text='PERSONAL').pack()
Label(f85, text='FRAME 6').pack()
Label(f85,text="AMARDEEP SINGH",font="times 15 bold").pack()
Label(f85,text="FATHER'SNAME:xyz").pack()
Label(f85,text="CITY:xyz").pack()
Label(f85,text="STATE:xyz").pack()
Label(f85,text="MOBILE NO.:1234569870").pack()
Button(f85, text='<-',bg="red", width=10,command=lambda:raise_frame(f34)).pack()
Button(f85, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f86, text='ACADEMICS').pack()
Label(f86, text='FRAME 7').pack()
Label(f86,text="AMARDEEP SINGH",font="times 15 bold").pack()
Label(f86,text="ERNO,:161B025").pack()
Label(f86,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f86,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f86,text="TOTAL =7.6",bg="blue").pack()
Button(f86, text='<-',bg="red", width=10,command=lambda:raise_frame(f34)).pack()
Button(f86, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()


Label(f87, text='PERSONAL').pack()
Label(f87, text='FRAME 6').pack()
Label(f87,text="AMANDEEP SINGH",font="times 15 bold").pack()
Label(f87,text="FATHER'SNAME:xyz").pack()
Label(f87,text="CITY:xyz").pack()
Label(f87,text="STATE:xyz").pack()
Label(f87,text="MOBILE NO.:1234569870").pack()
Button(f87, text='<-',bg="red", width=10,command=lambda:raise_frame(f35)).pack()
Button(f87, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f88, text='ACADEMICS').pack()
Label(f88, text='FRAME 7').pack()
Label(f88,text="AMANDEEP SINGH",font="times 15 bold").pack()
Label(f88,text="ERNO,:161B026").pack()
Label(f88,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f88,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f88,text="TOTAL =7.6",bg="blue").pack()
Button(f88, text='<-',bg="red", width=10,command=lambda:raise_frame(f35)).pack()
Button(f88, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()


Label(f89, text='PERSONAL').pack()
Label(f89, text='FRAME 6').pack()
Label(f89,text="SANDEEP SINGH",font="times 15 bold").pack()
Label(f89,text="FATHER'SNAME:xyz").pack()
Label(f89,text="CITY:xyz").pack()
Label(f89,text="STATE:xyz").pack()
Label(f89,text="MOBILE NO.:1234569870").pack()
Button(f89, text='<-',bg="red", width=10,command=lambda:raise_frame(f36)).pack()
Button(f89, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f90, text='ACADEMICS').pack()
Label(f90, text='FRAME 7').pack()
Label(f90,text="SANDEEP SINGH",font="times 15 bold").pack()
Label(f90,text="ERNO,:161B208").pack()
Label(f90,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f90,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f90,text="TOTAL =7.6",bg="blue").pack()
Button(f90, text='<-',bg="red", width=10,command=lambda:raise_frame(f36)).pack()
Button(f90, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()


Label(f91, text='PERSONAL').pack()
Label(f91, text='FRAME 6').pack()
Label(f91,text="AMAN RAI",font="times 15 bold").pack()
Label(f91,text="FATHER'SNAME:xyz").pack()
Label(f91,text="CITY:xyz").pack()
Label(f91,text="STATE:xyz").pack()
Label(f91,text="MOBILE NO.:1234569870").pack()
Button(f91, text='<-',bg="red", width=10,command=lambda:raise_frame(f37)).pack()
Button(f91, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()


Label(f92, text='ACADEMICS').pack()
Label(f92, text='FRAME 7').pack()
Label(f92,text="AMAN RAI",font="times 15 bold").pack()
Label(f92,text="ERNO,:161B024").pack()
Label(f92,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f92,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f92,text="TOTAL =7.6",bg="blue").pack()
Button(f92, text='<-',bg="red", width=10,command=lambda:raise_frame(f37)).pack()
Button(f92, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()


Label(f93, text='PERSONAL').pack()
Label(f93, text='FRAME 6').pack()
Label(f93,text="AMIT KUMAR",font="times 15 bold").pack()
Label(f93,text="FATHER'SNAME:xyz").pack()
Label(f93,text="CITY:xyz").pack()
Label(f93,text="STATE:xyz").pack()
Label(f93,text="MOBILE NO.:1234569870").pack()
Button(f93, text='<-',bg="red", width=10,command=lambda:raise_frame(f38)).pack()
Button(f93, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f94, text='ACADEMICS').pack()
Label(f94, text='FRAME 7').pack()
Label(f93,text="AMIT KUMAR",font="times 15 bold").pack()
Label(f94,text="ERNO,:161B28").pack()
Label(f94,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f94,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f94,text="TOTAL =7.6",bg="blue").pack()
Button(f94, text='<-',bg="red", width=10,command=lambda:raise_frame(f38)).pack()
Button(f94, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()


Label(f95, text='PERSONAL').pack()
Label(f95, text='FRAME 6').pack()
Label(f95,text="AKASH GUPTA",font="times 15 bold").pack()
Label(f95,text="FATHER'SNAME:xyz").pack()
Label(f95,text="CITY:xyz").pack()
Label(f95,text="STATE:xyz").pack()
Label(f95,text="MOBILE NO.:1234569870").pack()
Button(f95, text='<-',bg="red", width=10,command=lambda:raise_frame(f39)).pack()
Button(f95, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()


Label(f96, text='ACADEMICS').pack()
Label(f96, text='FRAME 7').pack()
Label(f93,text="AKASH GUPTA",font="times 15 bold").pack()
Label(f96,text="ERNO,:161B017").pack()
Label(f96,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f96,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f96,text="TOTAL =7.6",bg="blue").pack()
Button(f96, text='<-',bg="red", width=10,command=lambda:raise_frame(f39)).pack()
Button(f96, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()


Label(f97, text='PERSONAL').pack()
Label(f97, text='FRAME 6').pack()
Label(f93,text="AYUSH SRIVASTAVA",font="times 15 bold").pack()
Label(f97,text="FATHER'SNAME:xyz").pack()
Label(f97,text="CITY:xyz").pack()
Label(f97,text="STATE:xyz").pack()
Label(f97,text="MOBILE NO.:1234569870").pack()
Button(f97, text='<-',bg="red", width=10,command=lambda:raise_frame(f40)).pack()
Button(f97, text='<-',bg="red", width=10,command=lambda:raise_frame(f40)).pack()

Label(f98, text='ACADEMICS').pack()
Label(f98, text='FRAME 7').pack()
Label(f98,text="AYUSH SRIVASTAVA",font="times 15 bold").pack()
Label(f98,text="ERNO,:161B063").pack()
Label(f98,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f98,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f98,text="TOTAL =7.6",bg="blue").pack()
Button(f98, text='<-',bg="red",width=10, command=lambda:raise_frame(f40)).pack()
Button(f98, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()


Label(f99, text='PERSONAL').pack()
Label(f99, text='FRAME 6').pack()
Label(f99,text="AJITESH SINGH",font="times 15 bold").pack()
Label(f99,text="FATHER'SNAME:xyz").pack()
Label(f99,text="CITY:xyz").pack()
Label(f99,text="STATE:xyz").pack()
Label(f99,text="MOBILE NO.:1234569870").pack()
Button(f99, text='<-',bg="red", width=10,command=lambda:raise_frame(f41)).pack()
Button(f99, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()


Label(f100, text='ACADEMICS').pack()
Label(f100, text='FRAME 7').pack()
Label(f100,text="AJITESH SINGH",font="times 15 bold").pack()
Label(f100,text="ERNO,:161B016").pack()
Label(f100,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f100,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f100,text="TOTAL =7.6",bg="blue").pack()
Button(f100, text='<-',bg="red", width=10,command=lambda:raise_frame(f41)).pack()
Button(f100, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()


Label(f101, text='PERSONAL').pack()
Label(f101, text='FRAME 6').pack()
Label(f101,text="AYUSH JAIN",font="times 15 bold").pack()
Label(f101,text="FATHER'SNAME:xyz").pack()
Label(f101,text="CITY:xyz").pack()
Label(f101,text="STATE:xyz").pack()
Label(f101,text="MOBILE NO.:1234569870").pack()
Button(f101, text='<-',bg="red", width=10,command=lambda:raise_frame(f42)).pack()
Button(f101, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f102, text='ACADEMICS').pack()
Label(f102, text='FRAME 7').pack()
Label(f102,text="AYUSH JAIN",font="times 15 bold").pack()
Label(f102,text="ERNO,:161B060").pack()
Label(f102,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f102,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f102,text="TOTAL =7.6",bg="blue").pack()
Button(f102, text='<-',bg="red",width=10, command=lambda:raise_frame(f42)).pack()
Button(f102, text='<-',bg="red",width=10, command=lambda:raise_frame(f1)).pack()


Label(f103, text='PERSONAL').pack()
Label(f103, text='FRAME 6').pack()
Label(f103,text="AJAY SINGH",font="times 15 bold").pack()
Label(f103,text="FATHER'SNAME:xyz").pack()
Label(f103,text="CITY:xyz").pack()
Label(f103,text="STATE:xyz").pack()
Label(f103,text="MOBILE NO.:1234569870").pack()
Button(f103, text='<-',bg="red",width=10, command=lambda:raise_frame(f43)).pack()
Button(f103, text='<-',bg="red",width=10, command=lambda:raise_frame(f1)).pack()


Label(f104, text='ACADEMICS').pack()
Label(f104, text='FRAME 7').pack()
Label(f104,text="AJAY SINGH",font="times 15 bold").pack()
Label(f104,text="ERNO,:161B15").pack()
Label(f104,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f104,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f104,text="TOTAL =7.6",bg="blue").pack()
Button(f104, text='<-',bg="red",width=10, command=lambda:raise_frame(f43)).pack()
Button(f104, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()


Label(f105, text='PERSONAL').pack()
Label(f105, text='FRAME 6').pack()
Label(f105,text="SURYANSH SINGH",font="times 15 bold").pack()
Label(f105,text="FATHER'SNAME:xyz").pack()
Label(f105,text="CITY:xyz").pack()
Label(f105,text="STATE:xyz").pack()
Label(f105,text="MOBILE NO.:1234569870").pack()
Button(f105, text='<-',bg="red", width=10,command=lambda:raise_frame(f44)).pack()
Button(f105, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f106, text='ACADEMICS').pack()
Label(f106, text='FRAME 7').pack()
Label(f106,text="AJAY SINGH",font="times 15 bold").pack()
Label(f106,text="ERNO,:161E053").pack()
Label(f106,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f106,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f106,text="TOTAL =7.6",bg="blue").pack()
Button(f106, text='<-',bg="red", width=10,command=lambda:raise_frame(f44)).pack()
Button(f106, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()


Label(f107, text='PERSONAL').pack()
Label(f107, text='FRAME 6').pack()
Label(f107,text="VIVEK SINGH",font="times 15 bold").pack()
Label(f107,text="FATHER'SNAME:xyz").pack()
Label(f107,text="CITY:xyz").pack()
Label(f107,text="STATE:xyz").pack()
Label(f107,text="MOBILE NO.:1234569870").pack()
Button(f107, text='<-',bg="red", width=10,command=lambda:raise_frame(f45)).pack()
Button(f107, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f108, text='ACADEMICS').pack()
Label(f108, text='FRAME 7').pack()
Label(f108,text="VIVEK SINGH",font="times 15 bold").pack()
Label(f108,text="ERNO,:161E052").pack()
Label(f108,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f108,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f108,text="TOTAL =7.6",bg="blue").pack()
Button(f108, text='<-',bg="red", width=10,command=lambda:raise_frame(f45)).pack()
Button(f108, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()


Label(f109, text='PERSONAL').pack()
Label(f109, text='FRAME 6').pack()
Label(f109,text="ABHISHEK SINGH",font="times 15 bold").pack()
Label(f109,text="FATHER'SNAME:xyz").pack()
Label(f109,text="CITY:xyz").pack()
Label(f109,text="STATE:xyz").pack()
Label(f109,text="MOBILE NO.:1234569870").pack()
Button(f109, text='<-',bg="red", width=10,command=lambda:raise_frame(f46)).pack()
Button(f109, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f110, text='ACADEMICS').pack()
Label(f110, text='FRAME 7').pack()
Label(f109,text="ABHISHEK SINGH",font="times 15 bold").pack()
Label(f110,text="ERNO,:161B009").pack()
Label(f110,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f110,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f110,text="TOTAL =7.6",bg="blue").pack()
Button(f110, text='<-',bg="red", width=10,command=lambda:raise_frame(f46)).pack()
Button(f110, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f111, text='PERSONAL').pack()
Label(f111, text='FRAME 6').pack()
Label(f111,text="ABHISHEK SHARMA",font="times 15 bold").pack()
Label(f111,text="FATHER'SNAME:xyz").pack()
Label(f111,text="CITY:xyz").pack()
Label(f111,text="STATE:xyz").pack()
Label(f111,text="MOBILE NO.:1234569870").pack()
Button(f111, text='<-',bg="red", width=10,command=lambda:raise_frame(f47)).pack()
Button(f111, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f112, text='ACADEMICS').pack()
Label(f112, text='FRAME 7').pack()
Label(f112,text="ABHISHEK SHARMA",font="times 15 bold").pack()
Label(f112,text="ERNO,:161B008").pack()
Label(f112,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f112,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f112,text="TOTAL =7.6",bg="blue").pack()
Button(f112, text='<-',bg="red", width=10,command=lambda:raise_frame(f47)).pack()
Button(f112, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f113, text='PERSONAL').pack()
Label(f113, text='FRAME 6').pack()
Label(f113,text="ABHISHEK RATHORE",font="times 15 bold").pack()
Label(f113,text="FATHER'SNAME:xyz").pack()
Label(f113,text="CITY:xyz").pack()
Label(f113,text="STATE:xyz").pack()
Label(f113,text="MOBILE NO.:1234569870").pack()
Button(f113, text='<-',bg="red", width=10,command=lambda:raise_frame(f48)).pack()
Button(f113, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f114, text='ACADEMICS').pack()
Label(f114, text='FRAME 7').pack()
Label(f113,text="ABHISHEK RATHORE",font="times 15 bold").pack()
Label(f114,text="ERNO,:161B010").pack()
Label(f114,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f114,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f114,text="TOTAL =7.6",bg="blue").pack()
Button(f114, text='<-',bg="red", width=10,command=lambda:raise_frame(f48)).pack()
Button(f114, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f115, text='PERSONAL').pack()
Label(f115, text='FRAME 6').pack()
Label(f115,text="AKSHAY KUMAR",font="times 15 bold").pack()
Label(f115,text="FATHER'SNAME:xyz").pack()
Label(f115,text="CITY:xyz").pack()
Label(f115,text="STATE:xyz").pack()
Label(f115,text="MOBILE NO.:1234569870").pack()
Button(f115, text='<-',bg="red", width=10,command=lambda:raise_frame(f49)).pack()
Button(f115, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f116, text='ACADEMICS').pack()
Label(f116, text='FRAME 7').pack()
Label(f116,text="AKSHAY KUMAR",font="times 15 bold").pack()
Label(f116,text="ERNO,:161B021").pack()
Label(f116,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f116,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f116,text="TOTAL =7.6",bg="blue").pack()
Button(f116, text='<-',bg="red", width=10,command=lambda:raise_frame(f49)).pack()
Button(f116, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f117, text='PERSONAL').pack()
Label(f117, text='FRAME 6').pack()
Label(f117,text="AKSHAY SINGH",font="times 15 bold").pack()
Label(f117,text="FATHER'SNAME:xyz").pack()
Label(f117,text="CITY:xyz").pack()
Label(f117,text="STATE:xyz").pack()
Label(f117,text="MOBILE NO.:1234569870").pack()
Button(f117, text='<-',bg="red", width=10,command=lambda:raise_frame(f50)).pack()
Button(f117, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f118, text='ACADEMICS').pack()
Label(f118, text='FRAME 7').pack()
Label(f118,text="AKSHAY SINGH",font="times 15 bold").pack()
Label(f118,text="ERNO,:161B019").pack()
Label(f118,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f118,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f118,text="TOTAL =7.6",bg="blue").pack()
Button(f118, text='<-',bg="red", width=10,command=lambda:raise_frame(f50)).pack()
Button(f118, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f119, text='PERSONAL').pack()
Label(f119, text='FRAME 6').pack()
Label(f119,text="AKSHAY SHARMA",font="times 15 bold").pack()
Label(f119,text="FATHER'SNAME:xyz").pack()
Label(f119,text="CITY:xyz").pack()
Label(f119,text="STATE:xyz").pack()
Label(f119,text="MOBILE NO.:1234569870").pack()
Button(f119, text='<-',bg="red", width=10,command=lambda:raise_frame(f51)).pack()
Button(f119, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f120, text='ACADEMICS').pack()
Label(f120, text='FRAME 7').pack()
Label(f120,text="AKSHAY SHARMA",font="times 15 bold").pack()
Label(f120,text="ERNO,:161B021").pack()
Label(f120,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f120,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f120,text="TOTAL =7.6",bg="blue").pack()
Button(f120, text='<-',bg="red", width=10,command=lambda:raise_frame(f51)).pack()
Button(f120, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f121, text='PERSONAL').pack()
Label(f121, text='FRAME 6').pack()
Label(f121,text="ROHIT KUMAR",font="times 15 bold").pack()
Label(f121,text="FATHER'SNAME:xyz").pack()
Label(f121,text="CITY:xyz").pack()
Label(f121,text="STATE:xyz").pack()
Label(f121,text="MOBILE NO.:1234569870").pack()
Button(f121, text='<-',bg="red", width=10,command=lambda:raise_frame(f52)).pack()
Button(f121, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f122, text='ACADEMICS').pack()
Label(f122, text='FRAME 7').pack()
Label(f122,text="ROHIT KUMAR",font="times 15 bold").pack()
Label(f122,text="ERNO,:161B185").pack()
Label(f122,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f122,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f122,text="TOTAL =7.6",bg="blue").pack()
Button(f122, text='<-',bg="red", width=10,command=lambda:raise_frame(f52)).pack()
Button(f122, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f123, text='PERSONAL').pack()
Label(f123, text='FRAME 6').pack()
Label(f123,text="SOBHIT SHARMA",font="times 15 bold").pack()
Label(f123,text="FATHER'SNAME:xyz").pack()
Label(f123,text="CITY:xyz").pack()
Label(f123,text="STATE:xyz").pack()
Label(f123,text="MOBILE NO.:1234569870").pack()
Button(f123, text='<-',bg="red", width=10,command=lambda:raise_frame(f53)).pack()
Button(f123, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f124, text='ACADEMICS').pack()
Label(f124, text='FRAME 7').pack()
Label(f124,text="SOBHIT SHARMA",font="times 15 bold").pack()
Label(f124,text="ERNO,:161B210").pack()
Label(f124,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f124,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f124,text="TOTAL =7.6",bg="blue").pack()
Button(f124, text='<-',bg="red", width=10,command=lambda:raise_frame(f53)).pack()
Button(f124, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f125, text='PERSONAL').pack()
Label(f125, text='FRAME 6').pack()
Label(f125,text="DEEPAK SHARMA",font="times 15 bold").pack()
Label(f125,text="FATHER'SNAME:xyz").pack()
Label(f125,text="CITY:xyz").pack()
Label(f125,text="STATE:xyz").pack()
Label(f125,text="MOBILE NO.:1234569870").pack()
Button(f125, text='<-',bg="red", width=10,command=lambda:raise_frame(f54)).pack()
Button(f125, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()

Label(f126, text='ACADEMICS').pack()
Label(f126, text='FRAME 7').pack()
Label(f121,text="DEEPAK SHARMA",font="times 15 bold").pack()
Label(f126,text="ERNO,:161B087").pack()
Label(f126,text="SEMESTER 1=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f126,text="SEMESTER 2=SGPA:7.6   CGPA:7.6",bg="blue").pack()
Label(f126,text="TOTAL =7.6",bg="blue").pack()
Button(f126, text='<-',bg="red", width=10,command=lambda:raise_frame(f54)).pack()
Button(f126, text='<-',bg="red", width=10,command=lambda:raise_frame(f1)).pack()














raise_frame(f1)
root.mainloop()
